@echo off
echo Descargando JavaFX...
powershell -Command "& {Invoke-WebRequest -Uri 'https://download2.gluonhq.com/openjfx/21/openjfx-21_windows-x64_bin-sdk.zip' -OutFile 'javafx-sdk.zip'}"
echo Extrayendo JavaFX...
powershell -Command "& {Expand-Archive -Path 'javafx-sdk.zip' -DestinationPath '.' -Force}"
echo Ejecutando el juego...
java --module-path "javafx-sdk-21\lib" --add-modules javafx.controls,javafx.fxml,javafx.media -cp "target/classes" com.mycompany.juegomemoria.App
pause 